"""
AgroVox - Intent classification dataset generator.

Builds a labelled dataset of farmer queries (English, plus a smaller set of
Tamil queries which the pipeline translates to English before classification
- see src/translation/translator.py) across the 10 AgroVox intent classes.

The dataset is template-generated by combining crop/entity slots with
category-specific question patterns, which is a standard, transparent way to
bootstrap a first-generation intent dataset for an academic NLP lab project
before more real farmer queries are collected. Every row is a distinct,
grammatical sentence - not simple duplication.

Run: python data/generate_intents.py
"""
import os
import sys
import csv
import random

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
import config

random.seed(config.RANDOM_SEED)

CROPS = ["rice", "wheat", "maize", "cotton", "sugarcane", "groundnut",
         "tomato", "banana", "chilli", "blackgram"]
DISEASES = ["bacterial leaf blight", "rice blast", "late blight", "fusarium wilt",
            "powdery mildew", "panama wilt", "leaf curl virus"]
PESTS = ["brown planthopper", "stem borer", "whitefly", "fall armyworm", "pod borer", "thrips"]
FERTS = ["urea", "DAP", "MOP", "zinc sulphate", "NPK complex", "vermicompost"]
LOCATIONS = ["Coimbatore", "Madurai", "Thanjavur", "Salem", "Trichy", "Erode"]
SOILS = ["black cotton soil", "red soil", "alluvial soil", "sandy loam", "clayey soil"]

TEMPLATES = {
    "Crop Disease": [
        "My {crop} crop has yellow leaves, what disease could it be?",
        "What are the symptoms of {disease} in {crop}?",
        "How do I treat {disease} affecting my {crop} field?",
        "The leaves on my {crop} plants are turning brown and spotted, is this a disease?",
        "Is {disease} common in {crop} grown in {location}?",
        "My {crop} plants are wilting suddenly, could it be {disease}?",
        "How can I prevent {disease} in my {crop} field next season?",
        "Are there resistant {crop} varieties against {disease}?",
    ],
    "Fertilizer": [
        "What fertilizer is suitable for {crop} during the vegetative stage?",
        "How much {fert} should I apply to my {crop} field?",
        "When should I apply {fert} to {crop}?",
        "Is {fert} good for improving flowering in {crop}?",
        "What is the correct nutrient schedule for {crop} cultivation?",
        "Can I use {fert} and organic manure together for {crop}?",
        "My {crop} leaves look pale, should I apply {fert}?",
        "What micronutrients does {crop} need for better yield?",
    ],
    "Irrigation": [
        "How often should {crop} crops be irrigated?",
        "What is the best irrigation method for {crop} in {location}?",
        "Should I use drip irrigation for my {crop} field?",
        "How much water does {crop} need during flowering?",
        "My {crop} field is waterlogged, what should I do?",
        "Is alternate wetting and drying suitable for {crop}?",
        "When is the critical irrigation stage for {crop}?",
        "How do I schedule irrigation for {crop} during summer?",
    ],
    "Soil": [
        "What type of soil is best suited for {crop}?",
        "Is {soil} suitable for growing {crop}?",
        "How can I improve soil fertility for {crop} cultivation?",
        "What is the ideal soil pH for {crop}?",
        "My field has {soil}, which crops should I grow?",
        "How do I test my soil before planting {crop}?",
        "Does {crop} grow well in {soil} in {location}?",
        "How can I fix poor drainage in {soil}?",
    ],
    "Pest Management": [
        "How do I control {pest} in my {crop} field?",
        "What are the signs of {pest} infestation in {crop}?",
        "Is {pest} a common problem for {crop} in {location}?",
        "What organic methods control {pest} on {crop}?",
        "My {crop} leaves have holes, could it be {pest} damage?",
        "How can I prevent {pest} without using chemical pesticides?",
        "What natural predators help control {pest} in {crop} fields?",
        "When should I set pheromone traps for {pest} in {crop}?",
    ],
    "Cultivation": [
        "When is the best time to sow {crop} in {location}?",
        "What is the ideal spacing for planting {crop}?",
        "How long does {crop} take to mature after sowing?",
        "What cultivation practices improve {crop} yield?",
        "Can I intercrop {crop} with pulses?",
        "What seed rate should I use for {crop} in {location}?",
        "How do I prepare land before sowing {crop}?",
        "Which {crop} variety is recommended for {location}?",
    ],
    "Weather": [
        "Will heavy rain affect my {crop} crop this week?",
        "Should I delay fertilizer application because of rain forecast?",
        "How does a dry spell affect {crop} in the flowering stage?",
        "Is it safe to spray pesticide on {crop} before expected rain?",
        "What precautions should I take for {crop} during a heatwave?",
        "How does humidity increase disease risk in {crop}?",
        "Should I irrigate {crop} before an expected drought in {location}?",
        "Will frost damage my {crop} crop in {location}?",
    ],
    "Crop Information": [
        "What is the growth duration of {crop}?",
        "Tell me about {crop} cultivation in general.",
        "What season is best for growing {crop}?",
        "What are the main varieties of {crop} grown in {location}?",
        "What temperature range does {crop} need to grow well?",
        "Is {crop} a Kharif or Rabi crop?",
        "What is the market use of {crop} after harvest?",
        "How is {crop} propagated?",
    ],
    "Harvesting": [
        "When is the best time to harvest {crop}?",
        "How do I know if my {crop} is ready for harvesting?",
        "What are the signs of maturity in {crop}?",
        "How should I store {crop} after harvesting?",
        "What harvesting method is recommended for {crop}?",
        "How can I reduce post-harvest losses in {crop}?",
        "Should I harvest {crop} before or after rain?",
        "What moisture content is ideal for harvesting {crop}?",
    ],
    "General Agriculture": [
        "What is crop rotation and why is it useful?",
        "Can you explain why crop rotation matters for soil health?",
        "How can I start organic farming on my land?",
        "What are the first steps to convert my farm to organic methods?",
        "What government schemes support small farmers in {location}?",
        "Are there subsidy programs for small-scale farmers in {location}?",
        "How do I get a soil health card?",
        "What is the process for applying for a soil health card?",
        "What is Integrated Pest Management?",
        "Can you explain the basics of Integrated Pest Management?",
        "How can I improve overall farm productivity?",
        "What general practices boost overall productivity on a farm?",
        "What record-keeping practices help farm management?",
        "Why is record-keeping important for managing a farm well?",
        "Where can I get agricultural loans in {location}?",
        "What are my options for farm credit or loans near {location}?",
        "How do I register as a farmer for government benefits?",
        "What resources are available for new farmers starting out in {location}?",
    ],
}

# A handful of authentic Tamil-language queries per class (used to validate/
# demonstrate multilingual handling end-to-end; translated to English via the
# pipeline's translation module before being fed to the classifier).
TAMIL_EXAMPLES = {
    "Crop Disease": [
        "என் நெற்பயிரில் இலைகள் மஞ்சளாகிறது. என்ன செய்ய வேண்டும்?",
        "தக்காளி செடியில் இலைகள் கருகுகிறது, என்ன நோய்?",
    ],
    "Fertilizer": [
        "நெல் பயிருக்கு எந்த உரம் நல்லது?",
        "பருத்திக்கு யூரியா எவ்வளவு போடலாம்?",
    ],
    "Irrigation": [
        "தக்காளி பயிருக்கு எத்தனை முறை நீர் பாய்ச்ச வேண்டும்?",
        "கரும்பு பயிருக்கு துளி நீர்ப்பாசனம் நல்லதா?",
    ],
    "Soil": [
        "எனது வயலில் கருப்பு மண் உள்ளது, என்ன பயிர் செய்யலாம்?",
        "நிலக்கடலைக்கு எந்த மண் நல்லது?",
    ],
    "Pest Management": [
        "பருத்தியில் வெள்ளை ஈ தாக்குதலை எப்படி கட்டுப்படுத்துவது?",
        "நெல் பயிரில் தண்டு துளைப்பான் இருந்தால் என்ன செய்வது?",
    ],
}


def render(pattern: str) -> str:
    return pattern.format(
        crop=random.choice(CROPS),
        disease=random.choice(DISEASES),
        pest=random.choice(PESTS),
        fert=random.choice(FERTS),
        location=random.choice(LOCATIONS),
        soil=random.choice(SOILS),
    )


def main():
    rows = []
    seen = set()
    for label, templates in TEMPLATES.items():
        for template in templates:
            # generate several distinct fillings per template for a larger,
            # more robust training set
            variants = 6
            attempts = 0
            produced = 0
            while produced < variants and attempts < variants * 5:
                attempts += 1
                text = render(template)
                key = (label, text.lower())
                if key in seen:
                    continue
                seen.add(key)
                rows.append((text, label, "en"))
                produced += 1
        for ta_text in TAMIL_EXAMPLES.get(label, []):
            rows.append((ta_text, label, "ta"))

    random.shuffle(rows)
    out_path = config.INTENTS_CSV
    with open(out_path, "w", newline="", encoding="utf-8") as f:
        w = csv.writer(f)
        w.writerow(["text", "label", "language"])
        w.writerows(rows)

    print(f"Generated {len(rows)} intent examples across {len(TEMPLATES)} classes -> {out_path}")
    from collections import Counter
    counts = Counter(r[1] for r in rows)
    for label, c in counts.items():
        print(f"  {label:22s} : {c}")


if __name__ == "__main__":
    main()
