"""
AgroVox - Intent classification dataset generator.

Builds a labelled dataset of farmer queries (English, plus a smaller set of
Tamil queries which the pipeline translates to English before classification
- see src/translation/translator.py) across the 10 AgroVox intent classes.

The dataset is template-generated by combining crop/entity slots with
category-specific question patterns, which is a standard, transparent way to
bootstrap a first-generation intent dataset for an academic NLP lab project
before more real farmer queries are collected. Every row is a distinct,
grammatical sentence - not simple duplication.

Run: python data/generate_intents.py
"""
import os
import sys
import csv
import random

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
import config

random.seed(config.RANDOM_SEED)

CROPS = ["rice", "wheat", "maize", "cotton", "sugarcane", "groundnut",
         "tomato", "banana", "chilli", "blackgram"]
DISEASES = ["bacterial leaf blight", "rice blast", "late blight", "fusarium wilt",
            "powdery mildew", "panama wilt", "leaf curl virus"]
PESTS = ["brown planthopper", "stem borer", "whitefly", "fall armyworm", "pod borer", "thrips"]
FERTS = ["urea", "DAP", "MOP", "zinc sulphate", "NPK complex", "vermicompost"]
LOCATIONS = ["Coimbatore", "Madurai", "Thanjavur", "Salem", "Trichy", "Erode"]
SOILS = ["black cotton soil", "red soil", "alluvial soil", "sandy loam", "clayey soil"]

TEMPLATES = {
    "Crop Disease": [
        "My {crop} crop has yellow leaves, what disease could it be?",
        "My {crop} crop has yellow leaves in {location}.",
        "My {crop} crop has yellow leaves.",
        "The leaves on my {crop} plants are turning yellow and drying.",
        "Why are my {crop} leaves turning yellow?",
        "Yellowing leaves in my {crop} field in {location}.",
        "What are the symptoms of {disease} in {crop}?",
        "How do I treat {disease} affecting my {crop} field in {location}?",
        "The leaves on my {crop} plants are turning brown and spotted, is this a disease?",
        "Is {disease} common in {crop} grown in {location}?",
        "My {crop} plants are wilting suddenly, could it be {disease}?",
        "How can I prevent {disease} in my {crop} field next season?",
        "Are there resistant {crop} varieties against {disease}?",
        "White powdery fungus on {crop} leaves in {location}.",
        "Black spots and blight on {crop} foliage.",
        "How to cure fungal infection in {crop}?",
        "What fungicide should I spray for {disease} on {crop}?",
        "Root rot and leaf drying in {crop} plants.",
    ],
    "Fertilizer": [
        "What fertilizer is suitable for {crop} during the vegetative stage?",
        "How much {fert} should I apply to my {crop} field in {location}?",
        "When should I apply {fert} to {crop}?",
        "Is {fert} good for improving flowering in {crop}?",
        "What is the correct nutrient schedule for {crop} cultivation?",
        "Can I use {fert} and organic manure together for {crop}?",
        "My {crop} leaves look pale due to nutrient deficiency, should I apply {fert}?",
        "What micronutrients does {crop} need for better yield in {location}?",
        "Recommended dosage of {fert} for {crop} per acre.",
        "Nitrogen and phosphorus fertilizer requirements for {crop}.",
        "Foliar spray of micronutrients for {crop}.",
        "How to apply basal fertilizer for {crop}?",
        "Is urea application safe for {crop} at tillering stage?",
        "What is the NPK ratio recommended for {crop} in {location}?",
    ],
    "Irrigation": [
        "How often should {crop} crops be irrigated in {location}?",
        "What is the best irrigation method for {crop} in {location}?",
        "Should I use drip irrigation for my {crop} field?",
        "How much water does {crop} need during flowering stage?",
        "My {crop} field is waterlogged, what should I do?",
        "Is alternate wetting and drying suitable for {crop}?",
        "When is the critical irrigation stage for {crop}?",
        "How do I schedule irrigation for {crop} during summer in {location}?",
        "Water requirement and watering schedule for {crop}.",
        "Sprinkler vs flood irrigation for {crop}.",
        "How to prevent moisture stress in {crop} field?",
        "Irrigation interval for {crop} in dry weather.",
        "Does {crop} need standing water throughout its growth?",
        "Can I reduce water consumption for {crop} using drip lines?",
    ],
    "Soil": [
        "What type of soil is best suited for {crop}?",
        "Is {soil} suitable for growing {crop} in {location}?",
        "How can I improve soil fertility for {crop} cultivation?",
        "What is the ideal soil pH for {crop}?",
        "My field has {soil}, which crops should I grow in {location}?",
        "How do I test my soil before planting {crop}?",
        "Does {crop} grow well in {soil} in {location}?",
        "How can I fix poor drainage and salinity in {soil}?",
        "Soil preparation and organic matter addition for {crop} in {soil}.",
        "Nutrient management in {soil} for {crop} farming.",
        "Soil testing procedure and soil health management for {crop}.",
        "Characteristics of {soil} for agricultural crops.",
        "Is acidic soil harmful for {crop} root growth?",
        "How to enrich {soil} with farmyard manure for {crop}?",
    ],
    "Pest Management": [
        "How do I control {pest} in my {crop} field in {location}?",
        "What are the signs of {pest} infestation in {crop}?",
        "Is {pest} a common problem for {crop} in {location}?",
        "What organic methods control {pest} on {crop}?",
        "My {crop} leaves have holes, could it be {pest} damage?",
        "How can I prevent {pest} without using chemical pesticides?",
        "What natural predators help control {pest} in {crop} fields?",
        "When should I set pheromone traps for {pest} in {crop}?",
        "Insects and caterpillars attacking my {crop} in {location}.",
        "Small bugs eating {crop} leaves and shoots.",
        "Aphids and sucking pests on {crop} plants.",
        "Stem borer damaging {crop} stems and tillers.",
        "How to make neem seed kernel extract for pest control in {crop}?",
        "What insecticide is effective against {pest} on {crop}?",
    ],
    "Cultivation": [
        "When is the best time to sow {crop} in {location}?",
        "What is the ideal spacing for planting {crop}?",
        "How long does {crop} take to mature after sowing?",
        "What cultivation practices improve {crop} yield in {location}?",
        "Can I intercrop {crop} with pulses?",
        "What seed rate should I use for {crop} in {location}?",
        "How do I prepare land before sowing {crop}?",
        "Which {crop} variety is recommended for {location}?",
        "Transplanting techniques and nursery management for {crop}.",
        "Direct seeding vs transplanting for {crop} in {location}.",
        "Weeding and intercultural operations for {crop} cultivation.",
        "Crop management and agronomic practices for {crop}.",
        "What is the optimum planting density for {crop}?",
        "Steps for seed treatment before sowing {crop}.",
    ],
    "Weather": [
        "Will heavy rain affect my {crop} crop this week in {location}?",
        "Should I delay fertilizer application because of rain forecast in {location}?",
        "How does a dry spell affect {crop} in the flowering stage?",
        "Is it safe to spray pesticide on {crop} before expected rain?",
        "What precautions should I take for {crop} during a heatwave in {location}?",
        "How does high humidity increase disease risk in {crop}?",
        "Should I irrigate {crop} before an expected drought in {location}?",
        "Will frost or cold weather damage my {crop} crop in {location}?",
        "Impact of temperature and monsoon on {crop} growth.",
        "Weather forecast advisory for {crop} in {location}.",
        "Protecting {crop} from cyclonic wind and excess rain in {location}.",
        "How does dry climate affect {crop} pollination?",
        "Is high night temperature detrimental to {crop} grain filling?",
        "What to do if unseasonal rains occur during {crop} flowering?",
    ],
    "Crop Information": [
        "What is the growth duration of {crop}?",
        "Tell me about {crop} cultivation in general.",
        "What season is best for growing {crop} in {location}?",
        "What are the main varieties of {crop} grown in {location}?",
        "What temperature range does {crop} need to grow well?",
        "Is {crop} a Kharif or Rabi crop?",
        "What is the economic importance and market use of {crop}?",
        "How is {crop} propagated and cultivated in {location}?",
        "General overview and agronomic profile of {crop}.",
        "Yield potential and characteristics of {crop} varieties.",
        "Major producing regions for {crop} in {location}?",
        "Basic requirements and crop duration for {crop}.",
        "What is the botanical classification and life cycle of {crop}?",
        "Is {crop} suitable for cultivation in drought-prone areas?",
    ],
    "Harvesting": [
        "When is the best time to harvest {crop} in {location}?",
        "How do I know if my {crop} is ready for harvesting?",
        "What are the signs of maturity in {crop}?",
        "How should I store {crop} after harvesting to prevent damage?",
        "What harvesting method and machinery is recommended for {crop}?",
        "How can I reduce post-harvest losses in {crop} in {location}?",
        "Should I harvest {crop} before or after rain in {location}?",
        "What moisture content is ideal for harvesting and storing {crop}?",
        "Post-harvest processing and drying methods for {crop}.",
        "Storage conditions and bagging for harvested {crop}.",
        "Signs that {crop} has reached physiological maturity.",
        "Threshing and cleaning techniques for {crop} after harvest.",
        "How to protect stored {crop} grains from storage pests?",
        "What is the shelf life of harvested {crop} under standard storage?",
    ],
    "General Agriculture": [
        "What is crop rotation and why is it useful for {crop} farmers?",
        "Can you explain why crop rotation matters for soil health in {location}?",
        "How can I start organic farming on my land in {location}?",
        "What are the first steps to convert my farm to organic methods for {crop}?",
        "What government schemes support small farmers in {location}?",
        "Are there subsidy programs for small-scale {crop} farmers in {location}?",
        "How do I get a soil health card from the agricultural office in {location}?",
        "What is the process for applying for a PM-Kisan subsidy in {location}?",
        "What is Integrated Pest Management and how does it work for {crop}?",
        "Can you explain the basic principles of sustainable farming for {crop} in {location}?",
        "How can I improve overall farm productivity and income in {location}?",
        "What general farm management practices boost crop returns for {crop}?",
        "What record-keeping practices help farm management in {location}?",
        "Where can I get agricultural loans and crop insurance in {location}?",
        "What are my options for Kisan Credit Card loans near {location}?",
        "How do I register as a farmer for government benefits in {location}?",
        "What are the best agricultural extension services available in {location}?",
        "How does precision agriculture benefit small farmers in {location}?",
    ],
}

# Authentic Tamil-language queries per class
TAMIL_EXAMPLES = {
    "Crop Disease": [
        "என் நெற்பயிரில் இலைகள் மஞ்சளாகிறது. என்ன செய்ய வேண்டும்?",
        "தக்காளி செடியில் இலைகள் கருகுகிறது, என்ன நோய்?",
        "பருத்தி செடியில் இலை கருகல் நோய் எப்படி கட்டுப்படுத்துவது?",
        "வாழையில் பனாமா வாடல் நோய் அறிகுறி என்ன?",
    ],
    "Fertilizer": [
        "நெல் பயிருக்கு எந்த உரம் நல்லது?",
        "பருத்திக்கு யூரியா எவ்வளவு போடலாம்?",
        "தக்காளிக்கு என்பிகே உரம் எப்போது இட வேண்டும்?",
        "நிலக்கடலைக்கு ஜிப்சம் உரம் எப்போது இட வேண்டும்?",
    ],
    "Irrigation": [
        "தக்காளி பயிருக்கு எத்தனை முறை நீர் பாய்ச்ச வேண்டும்?",
        "கரும்பு பயிருக்கு துளி நீர்ப்பாசனம் நல்லதா?",
        "நெல் பயிருக்கு நீர் மேலாண்மை எப்படி செய்வது?",
        "வாழை பயிருக்கு எவ்வளவு தண்ணீர் தேவை?",
    ],
    "Soil": [
        "எனது வயலில் கருப்பு மண் உள்ளது, என்ன பயிர் செய்யலாம்?",
        "நிலக்கடலைக்கு எந்த மண் நல்லது?",
        "செம்மண்ணில் என்ன பயிர் நன்கு வளரும்?",
        "மண் பரிசோதனை செய்வது எப்படி?",
    ],
    "Pest Management": [
        "பருத்தியில் வெள்ளை ஈ தாக்குதலை எப்படி கட்டுப்படுத்துவது?",
        "நெல் பயிரில் தண்டு துளைப்பான் இருந்தால் என்ன செய்வது?",
        "மிளகாயில் அசுவினி பூச்சி கட்டுப்பாடு எப்படி?",
        "சோளத்தில் படைப்புழு தாக்குதலை தடுப்பது எப்படி?",
    ],
    "Cultivation": [
        "நெல் நடவு செய்ய சரியான பருவம் எது?",
        "உளுந்து விதைப்பு முறை எப்படி?",
        "பருத்தி சாகுபடி முறைகள் என்ன?",
        "தக்காளி செடி இடைவெளி எவ்வளவு இருக்க வேண்டும்?",
    ],
    "Weather": [
        "மழைக்காலத்தில் உரம் இடலாமா?",
        "கடும் வெயிலில் பயிரை எப்படி பாதுகாப்பது?",
        "வானிலை முன்னறிவிப்பு விவரங்கள் என்ன?",
        "பனிப்பொழிவால் பயிர் பாதிக்கப்படுமா?",
    ],
    "Crop Information": [
        "நெல் பயிரின் வயது என்ன?",
        "கரும்பு பயிர் வளர்ச்சி காலம் எவ்வளவு?",
        "நிலக்கடலை ரகங்கள் என்னென்ன உள்ளன?",
        "வாழை சாகுபடி பற்றி தகவல் கூறுங்கள்.",
    ],
    "Harvesting": [
        "நெல் அறுவடைக்கு தயாராக இருப்பது எப்படி தெரியும்?",
        "உளுந்து எப்போது அறுவடை செய்ய வேண்டும்?",
        "அறுவடைக்கு பின் தானியங்களை சேமிப்பது எப்படி?",
        "கரும்பு அறுவடைக்கு உகந்த காலம் எது?",
    ],
    "General Agriculture": [
        "விவசாய கடன் பெறுவது எப்படி?",
        "இயற்கை விவசாயம் தொடங்குவது எப்படி?",
        "விவசாய மானிய திட்டங்கள் என்னென்ன உள்ளன?",
        "பயிர் சுழற்சி என்றால் என்ன?",
    ],
}


def render(pattern: str) -> str:
    return pattern.format(
        crop=random.choice(CROPS),
        disease=random.choice(DISEASES),
        pest=random.choice(PESTS),
        fert=random.choice(FERTS),
        location=random.choice(LOCATIONS),
        soil=random.choice(SOILS),
    )


def main():
    rows = []
    seen = set()
    for label, templates in TEMPLATES.items():
        for template in templates:
            # generate several distinct fillings per template for a larger,
            # more robust training set
            variants = 6
            attempts = 0
            produced = 0
            while produced < variants and attempts < variants * 5:
                attempts += 1
                text = render(template)
                key = (label, text.lower())
                if key in seen:
                    continue
                seen.add(key)
                rows.append((text, label, "en"))
                produced += 1
        for ta_text in TAMIL_EXAMPLES.get(label, []):
            rows.append((ta_text, label, "ta"))

    random.shuffle(rows)
    out_path = config.INTENTS_CSV
    with open(out_path, "w", newline="", encoding="utf-8") as f:
        w = csv.writer(f)
        w.writerow(["text", "label", "language"])
        w.writerows(rows)

    print(f"Generated {len(rows)} intent examples across {len(TEMPLATES)} classes -> {out_path}")
    from collections import Counter
    counts = Counter(r[1] for r in rows)
    for label, c in counts.items():
        print(f"  {label:22s} : {c}")


if __name__ == "__main__":
    main()
